//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo.ServerJs.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionTexts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zoo.ServerJs.Resources.ExceptionTexts", typeof(ExceptionTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компонент с названием &apos;{0}&apos; уже зарегистрирован.
        /// </summary>
        internal static string ComponentWithNameAlreadyRegisteredFormat {
            get {
                return ResourceManager.GetString("ComponentWithNameAlreadyRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Провайдер Http клиентов уже зарегистрирован.
        /// </summary>
        internal static string HttpClientProviderIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("HttpClientProviderIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рабочий Js класс с именем {0} уже зарегистрирован.
        /// </summary>
        internal static string JsWorkerWithNameAlreadyRegisteredFormat {
            get {
                return ResourceManager.GetString("JsWorkerWithNameAlreadyRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод &apos;{0}&apos; Js класса &apos;{1}&apos; содержит {2} параметров, но был вызван с {3} параметрами..
        /// </summary>
        internal static string MethodWasCalledWithLessParamsFormat {
            get {
                return ResourceManager.GetString("MethodWasCalledWithLessParamsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод с названием &apos;{0}&apos; не существует в группе методов класса &apos;{1}&apos;.
        /// </summary>
        internal static string MethodWithNameDoesNotExistInWorkerFormat {
            get {
                return ResourceManager.GetString("MethodWithNameDoesNotExistInWorkerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перед добавлением удаленного Апи, необходимо предоставить фабрику Http клиента. Воспользуйтесь методом {0}.
        /// </summary>
        internal static string NeedSettingHttpClientBeforeUseMethodFormat {
            get {
                return ResourceManager.GetString("NeedSettingHttpClientBeforeUseMethodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В Js классе {0} не зарегистрировано ни одного метода.
        /// </summary>
        internal static string NoMethodsInWorkerFormat {
            get {
                return ResourceManager.GetString("NoMethodsInWorkerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В системе нет зарегистрированного рабочего класса с именем &apos;{0}&apos;.
        /// </summary>
        internal static string NoWorkerWithNameRegisteredFormat {
            get {
                return ResourceManager.GetString("NoWorkerWithNameRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Персистентное хранилище данных уже установлено.
        /// </summary>
        internal static string PersistedStorageIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("PersistedStorageIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаленное апи с названием &apos;{0}&apos; уже зарегистрировано.
        /// </summary>
        internal static string RemoteApiWithNameAlreadyRegisteredFormat {
            get {
                return ResourceManager.GetString("RemoteApiWithNameAlreadyRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хранилище для скриптов уже установлено.
        /// </summary>
        internal static string ScriptStorageIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("ScriptStorageIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервис с типом {0} не зарегистрирован в контейнере зависимостей, для начала зарегистрируйте его в коллекции сервисов..
        /// </summary>
        internal static string TypeOfServiceNotRegisteredInServiceCollectionFormat {
            get {
                return ResourceManager.GetString("TypeOfServiceNotRegisteredInServiceCollectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать имя рабочего класса.
        /// </summary>
        internal static string WorkerNameIsRequired {
            get {
                return ResourceManager.GetString("WorkerNameIsRequired", resourceCulture);
            }
        }
    }
}
