//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clt.Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clt.Contract.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный Email адрес.
        /// </summary>
        public static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать Email.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка. {0}.
        /// </summary>
        public static string ErrorOccuredFormat {
            get {
                return ResourceManager.GetString("ErrorOccuredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не найден по указанному идентификатору.
        /// </summary>
        public static string FileIsNotFoundById {
            get {
                return ResourceManager.GetString("FileIsNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не является изображением.
        /// </summary>
        public static string FileIsNotImage {
            get {
                return ResourceManager.GetString("FileIsNotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель является пустым объектом.
        /// </summary>
        public static string ModelIsNullObject {
            get {
                return ResourceManager.GetString("ModelIsNullObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель валидна.
        /// </summary>
        public static string ModelIsValid {
            get {
                return ResourceManager.GetString("ModelIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный Email уже занят другим пользователем.
        /// </summary>
        public static string ThisEmailIsAlreadyTaken {
            get {
                return ResourceManager.GetString("ThisEmailIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный номер телефона уже занят другим пользователем.
        /// </summary>
        public static string ThisPhoneNumberIsAlreadyTaken {
            get {
                return ResourceManager.GetString("ThisPhoneNumberIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный номер телефона уже занят другим пользователем.
        /// </summary>
        public static string ThisPhoneNumberIsAlreadyTakenByOtherUser {
            get {
                return ResourceManager.GetString("ThisPhoneNumberIsAlreadyTakenByOtherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный номер телефона уже занят другим пользователем.
        /// </summary>
        public static string ThisPhoneNumberIsAlreadyTakenByOtherUser1 {
            get {
                return ResourceManager.GetString("ThisPhoneNumberIsAlreadyTakenByOtherUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать Uri.
        /// </summary>
        public static string UriIsRequired {
            get {
                return ResourceManager.GetString("UriIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь найден.
        /// </summary>
        public static string UserFound {
            get {
                return ResourceManager.GetString("UserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать идентификатор пользователя.
        /// </summary>
        public static string UserIdentifierMustBeProvided {
            get {
                return ResourceManager.GetString("UserIdentifierMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать идентификатор пользователя.
        /// </summary>
        public static string UserIdIsRequired {
            get {
                return ResourceManager.GetString("UserIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не найден по указанному идентификатору.
        /// </summary>
        public static string UserIsNotFoundByIdentifier {
            get {
                return ResourceManager.GetString("UserIsNotFoundByIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не найден.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не являетесь администратором.
        /// </summary>
        public static string YouAreNotAnAdministrator {
            get {
                return ResourceManager.GetString("YouAreNotAnAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не являетесь администратором или продавцом..
        /// </summary>
        public static string YouAreNotAnAdministratorOrSeller {
            get {
                return ResourceManager.GetString("YouAreNotAnAdministratorOrSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не авторизованы.
        /// </summary>
        public static string YouAreNotAuthorized {
            get {
                return ResourceManager.GetString("YouAreNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете редактировать пользователя Root.
        /// </summary>
        public static string YouCantEditRootUser {
            get {
                return ResourceManager.GetString("YouCantEditRootUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете редактировать пользователя, так как он является администратором.
        /// </summary>
        public static string YouCantEditUserBecauseHeIsAdministrator {
            get {
                return ResourceManager.GetString("YouCantEditUserBecauseHeIsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете редактировать пользователя, так как он является Супер-Администратором.
        /// </summary>
        public static string YouCantEditUserBecauseHeIsSuperAdministrator {
            get {
                return ResourceManager.GetString("YouCantEditUserBecauseHeIsSuperAdministrator", resourceCulture);
            }
        }
    }
}
