//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo.GenericUserInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionTexts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zoo.GenericUserInterface.Resources.ExceptionTexts", typeof(ExceptionTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array types are not supported, use SetMultipleDropDownList method for array types.
        /// </summary>
        internal static string ArrayTypesAreNotSupportedSetMultipleDropDownList {
            get {
                return ResourceManager.GetString("ArrayTypesAreNotSupportedSetMultipleDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете применить метод MultipleDropDownFor к свойству, которое не является массивом..
        /// </summary>
        internal static string CantImplementMultipleDropDownForToNotEnumerableProperty {
            get {
                return ResourceManager.GetString("CantImplementMultipleDropDownForToNotEnumerableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете установить выпадающий список к свойству {0}, которое является перечислением. Данная операция не имеет смысла, так как выпадающий список заполняется автоматически из типа перечисления..
        /// </summary>
        internal static string CantImplementSetDropListNameToEnumPropertyFormat {
            get {
                return ResourceManager.GetString("CantImplementSetDropListNameToEnumPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете установить выпадающий список с единственным выбором на свойство {0}. Так как его тип данных не является примитивным..
        /// </summary>
        internal static string CantSetDropListForPropertyThatIsNotPrimitiveFormat {
            get {
                return ResourceManager.GetString("CantSetDropListForPropertyThatIsNotPrimitiveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете установить выпадающий список с единственным выбором на свойство, тип которого не является примитивным.
        /// </summary>
        internal static string CantSetDropListNotOnPrimitives {
            get {
                return ResourceManager.GetString("CantSetDropListNotOnPrimitives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете установить выпадающий список с множественным выбором на свойство, тип которого не является примитивным. Cвойство: {0}. Тип данных: {1}.
        /// </summary>
        internal static string CantSetMultipleDropListNotOnPrimitivesFormat {
            get {
                return ResourceManager.GetString("CantSetMultipleDropListNotOnPrimitivesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классы со свойствами Многомерные массивы не поддерживаются.
        /// </summary>
        internal static string ClassesWithMultiDimensionalArrayPropertiesAreNotSupported {
            get {
                return ResourceManager.GetString("ClassesWithMultiDimensionalArrayPropertiesAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Провайдер для автокомплита с типом данным {0} не зарегистрирован.
        /// </summary>
        internal static string DataProviderForAutoCompletionNotRegisteredFormat {
            get {
                return ResourceManager.GetString("DataProviderForAutoCompletionNotRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Провайдер данных с типом {0} не зарегистрирован.
        /// </summary>
        internal static string DataProviderWithTypeNotRegisteredFormat {
            get {
                return ResourceManager.GetString("DataProviderWithTypeNotRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dont use GetBlockBuilderForCollection on collections of chars. Use ordinary string property..
        /// </summary>
        internal static string DontUseGetBlockBuilderForCollectionOnCollectionsOfChars {
            get {
                return ResourceManager.GetString("DontUseGetBlockBuilderForCollectionOnCollectionsOfChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Non complex types are not supported.
        /// </summary>
        internal static string NonComplexTypesAreNotSupported {
            get {
                return ResourceManager.GetString("NonComplexTypesAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переопределение интерфейса для типа {0} уже задано.
        /// </summary>
        internal static string OverridingForTypeIsAlreadySetFormat {
            get {
                return ResourceManager.GetString("OverridingForTypeIsAlreadySetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только к типу данных строка можно установить элемент Password.
        /// </summary>
        internal static string PasswordCanBeSetOnlyOnStrings {
            get {
                return ResourceManager.GetString("PasswordCanBeSetOnlyOnStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recursive types are not supported.
        /// </summary>
        internal static string RecursiveTypesAreNotSupported {
            get {
                return ResourceManager.GetString("RecursiveTypesAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только к типу данных строка можно установить элемент TextArea.
        /// </summary>
        internal static string TextAreaCanBeSetOnlyOnStrings {
            get {
                return ResourceManager.GetString("TextAreaCanBeSetOnlyOnStrings", resourceCulture);
            }
        }
    }
}
